@extends('layouts.app')

@section('title', 'Reports & Analytics')
@section('page-title', 'Reports & Analytics')

@section('content')
<div class="page-header">
    <div>
        <h1>Reports & Analytics</h1>
        <p>Generate and view counseling session reports</p>
    </div>
</div>

<div style="display:grid;grid-template-columns:340px 1fr;gap:24px;align-items:start;">

    {{-- Generate Report Panel --}}
    <div class="card">
        <div class="card-header"><span class="card-title">Generate Report</span></div>
        <div class="card-body">
            <form method="POST" action="{{ route('reports.generate') }}">
                @csrf
                <div class="form-group">
                    <label>Report Type *</label>
                    <select name="report_type" class="form-control" required>
                        <option value="monthly">Monthly Summary</option>
                        <option value="session_summary">Session Summary</option>
                        <option value="counselor_workload">Counselor Workload</option>
                        <option value="student_visit">Student Visit History</option>
                        <option value="annual">Annual Report</option>
                    </select>
                </div>

                <div class="form-group">
                    <label>Date From</label>
                    <input type="date" name="date_from" class="form-control" value="{{ now()->startOfMonth()->format('Y-m-d') }}">
                </div>

                <div class="form-group">
                    <label>Date To</label>
                    <input type="date" name="date_to" class="form-control" value="{{ now()->format('Y-m-d') }}">
                </div>

                <button type="submit" class="btn btn-primary w-full">
                    <i class="ph-bold ph-chart-bar"></i> Generate Report
                </button>
            </form>
        </div>
    </div>

    {{-- Past Reports --}}
    <div class="card">
        <div class="card-header"><span class="card-title">Report History</span></div>
        <div class="table-wrap">
            @if($reports->isEmpty())
            <div class="empty-state">
                <i class="ph ph-file-text"></i>
                <h3>No reports generated yet</h3>
                <p>Use the form on the left to generate your first report.</p>
            </div>
            @else
            <table>
                <thead>
                    <tr>
                        <th>Report</th>
                        <th>Type</th>
                        <th>Date Range</th>
                        <th>Generated By</th>
                        <th>Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reports as $report)
                    <tr>
                        <td class="font-semibold">{{ $report->report_title }}</td>
                        <td>
                            <span class="badge badge-secondary" style="text-transform:capitalize;">
                                {{ str_replace('_', ' ', $report->report_type) }}
                            </span>
                        </td>
                        <td class="text-sm text-muted">
                            @if($report->date_from && $report->date_to)
                            {{ $report->date_from->format('M d') }} – {{ $report->date_to->format('M d, Y') }}
                            @else
                            All time
                            @endif
                        </td>
                        <td>{{ $report->generatedByUser->full_name }}</td>
                        <td class="text-sm text-muted">{{ $report->created_at->format('M d, Y h:i A') }}</td>
                        <td>
                            <span class="badge badge-{{ $report->status === 'completed' ? 'success' : 'warning' }}">
                                {{ ucfirst($report->status) }}
                            </span>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            @endif
        </div>

        @if($reports->hasPages())
        <div style="padding:16px 20px;border-top:1px solid var(--border-light);">
            {{ $reports->links() }}
        </div>
        @endif
    </div>
</div>
@endsection
