@extends('layouts.app')

@section('title', 'Report: ' . $report->report_title)
@section('page-title', 'Report Results')
@section('breadcrumb', 'Reports / ' . $report->report_title)

@section('content')
<div class="page-header">
    <div>
        <h1>{{ $report->report_title }}</h1>
        <p>
            Generated by {{ $report->generatedByUser->full_name }} on {{ $report->created_at->format('F j, Y h:i A') }}
            @if($dateFrom && $dateTo)
            · Period: {{ $dateFrom->format('M d, Y') }} – {{ $dateTo->format('M d, Y') }}
            @endif
        </p>
    </div>
    <a href="{{ route('reports.index') }}" class="btn btn-outline">
        <i class="ph-bold ph-arrow-left"></i> Back to Reports
    </a>
</div>

@if($report->report_type === 'monthly' || $report->report_type === 'annual')
<div class="stats-grid" style="margin-bottom:24px;">
    <div class="stat-card">
        <div class="stat-icon blue"><i class="ph-bold ph-calendar"></i></div>
        <div class="stat-info">
            <div class="stat-value">{{ $reportData['total_appointments'] ?? 0 }}</div>
            <div class="stat-label">Total Appointments</div>
        </div>
    </div>
    <div class="stat-card">
        <div class="stat-icon green"><i class="ph-bold ph-chats-circle"></i></div>
        <div class="stat-info">
            <div class="stat-value">{{ $reportData['total_sessions'] ?? 0 }}</div>
            <div class="stat-label">Total Sessions</div>
        </div>
    </div>
    <div class="stat-card">
        <div class="stat-icon teal"><i class="ph-bold ph-student"></i></div>
        <div class="stat-info">
            <div class="stat-value">{{ $reportData['new_students'] ?? 0 }}</div>
            <div class="stat-label">New Students Registered</div>
        </div>
    </div>
</div>

@if(!empty($reportData['appointment_status']))
<div class="card mb-4">
    <div class="card-header"><span class="card-title">Appointment Status Breakdown</span></div>
    <div class="card-body">
        <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px;">
            @foreach($reportData['appointment_status'] as $status => $count)
            @php $colors=['pending'=>'warning','approved'=>'success','completed'=>'info','cancelled'=>'danger','no_show'=>'secondary','rescheduled'=>'primary']; @endphp
            <div style="text-align:center;padding:16px;background:var(--surface);border-radius:12px;border:1px solid var(--border-light);">
                <div style="font-size:26px;font-weight:700;">{{ $count }}</div>
                <div style="font-size:12px;margin-top:4px;">
                    <span class="badge badge-{{ $colors[$status] ?? 'secondary' }}">{{ ucfirst(str_replace('_',' ',$status)) }}</span>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>
@endif

@elseif($report->report_type === 'session_summary')
<div class="stats-grid" style="margin-bottom:24px;">
    <div class="stat-card">
        <div class="stat-icon blue"><i class="ph-bold ph-chats-circle"></i></div>
        <div class="stat-info">
            <div class="stat-value">{{ $reportData['total_sessions'] ?? 0 }}</div>
            <div class="stat-label">Total Sessions</div>
        </div>
    </div>
    <div class="stat-card">
        <div class="stat-icon green"><i class="ph-bold ph-check-circle"></i></div>
        <div class="stat-info">
            <div class="stat-value">{{ $reportData['completed'] ?? 0 }}</div>
            <div class="stat-label">Completed</div>
        </div>
    </div>
    <div class="stat-card">
        <div class="stat-icon amber"><i class="ph-bold ph-x-circle"></i></div>
        <div class="stat-info">
            <div class="stat-value">{{ $reportData['cancelled'] ?? 0 }}</div>
            <div class="stat-label">Cancelled</div>
        </div>
    </div>
</div>

@elseif($report->report_type === 'counselor_workload')
<div class="card">
    <div class="card-header"><span class="card-title">Counselor Workload Report</span></div>
    <div class="table-wrap">
        <table>
            <thead>
                <tr>
                    <th>Counselor</th>
                    <th>Department</th>
                    <th>Appointments</th>
                    <th>Sessions</th>
                    <th>Load</th>
                </tr>
            </thead>
            <tbody>
                @forelse($reportData['counselors'] ?? [] as $counselor)
                <tr>
                    <td>
                        <div class="flex items-center gap-2">
                            <div class="avatar">{{ $counselor->user->initials }}</div>
                            <div>
                                <div class="font-semibold">{{ $counselor->user->full_name }}</div>
                                <div class="text-sm text-muted">{{ $counselor->specialization }}</div>
                            </div>
                        </div>
                    </td>
                    <td>{{ $counselor->department?->department_code ?? '—' }}</td>
                    <td>{{ $counselor->appointments_count }}</td>
                    <td>{{ $counselor->sessions_count }}</td>
                    <td>
                        @php
                            $load = $counselor->sessions_count;
                            $color = $load > 20 ? 'danger' : ($load > 10 ? 'warning' : 'success');
                            $label = $load > 20 ? 'High' : ($load > 10 ? 'Moderate' : 'Low');
                        @endphp
                        <span class="badge badge-{{ $color }}">{{ $label }}</span>
                    </td>
                </tr>
                @empty
                <tr><td colspan="5" class="text-muted" style="text-align:center;padding:24px;">No data found</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>
</div>

@elseif($report->report_type === 'student_visit')
<div class="card">
    <div class="card-header"><span class="card-title">Student Visit History Report</span></div>
    <div class="table-wrap">
        <table>
            <thead>
                <tr>
                    <th>Student</th>
                    <th>Student No.</th>
                    <th>Course</th>
                    <th>Sessions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($reportData['students'] ?? [] as $student)
                <tr>
                    <td>
                        <div class="flex items-center gap-2">
                            <div class="avatar">{{ $student->user->initials }}</div>
                            <span class="font-semibold">{{ $student->user->full_name }}</span>
                        </div>
                    </td>
                    <td>{{ $student->student_num }}</td>
                    <td>{{ Str::limit($student->course, 35) }}</td>
                    <td><span class="badge badge-info">{{ $student->sessions_count }}</span></td>
                </tr>
                @empty
                <tr><td colspan="4" class="text-muted" style="text-align:center;padding:24px;">No data found</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>
</div>
@endif

@endsection
